language: C

matrix:
  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-5
#            - gfortran-5
#      env:
#         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
#
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#            - gfortran-6
#      env:
#        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get update
    - sudo apt-get install realpath
    - sudo apt-get install build-essential cmake gfortran
    - sudo apt-get install ruby ruby-dev
    - sudo apt-get install fuse
    - sudo apt-get install libnotify-dev
    - sudo apt-get install qt5-default libqt5serialport5-dev
    - sudo apt-get install libudev1 libudev-dev
    - gem install fpm

script:
    - make release -j `nproc`
    - # make prerelease -j `nproc`
    - # make debug -j `nproc`
    - make qt_apps -j `nproc`
    - # make qt_debs -j `nproc`
    - # make qt_appimages -j `nproc`

